language: csharp  
sudo: required  
dist: trusty
mono: none
dotnet: 2.0.0  
after_success:
  - ./e2e-tests.sh
script:
  - dotnet restore
  - dotnet build 
  - dotnet test Contentful.Core.Tests/Contentful.Core.Tests.csproj
  - dotnet test Contentful.AspNetCore.Tests/Contentful.AspNetCore.Tests.csproj